# Generated by Django 3.1.7 on 2021-04-10 14:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210410_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='pub_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
