# Generated by Django 3.2.7 on 2021-10-04 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210413_1829'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
        migrations.DeleteModel(
            name='FAQ',
        ),
    ]
